
services:
  
  maestro:
    image: ngnix:latest
    ports:
      - 1234:80
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro

  worker0X:
    image: hashicorp/http-echo
    command: "-text='Sla Piá'"

  worker1X:
    image: hashicorp/http-echo
    command: "-text='OPa bão!'"

  worker2X:
    image: hashicorp/http-echo
    command: "-text='LalaLa'"



