

events {
    worker_connections 1024;
}

    http {
        upstream oi {
            server worker0:5678;
            server worker1:5678;
            server worker2:5678;
        }
    };

    server { 
        listen 80;
        location ./; 
        proxy_pass http://oi;
    };
    