events {
    worker_connections 1024;
}

http {
    upstream apiapi {
        server api1:1010;
        server api2:1010;
        server api3:1010;
        server api4:1010;
        server api5:1010;
    }

    server {
        listen 80;
        location /api
        proxy_pass http://apiapi;
    }
}